[package]
name = "demux"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"

[[bin]]
name = "demux"
path = "src/bin/main.rs"

[lib]
name = "demux"
path = "src/lib.rs"

[dependencies]
iced = { version = "0.14.0", features = ["tokio"] }
rfd = "0.17.2"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "fs", "signal", "process", "time"] }
tracing = { version = "0.1.44", features = ["log"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json", "fmt"] }
